from distutils.core import setup

setup(
    name='pydl',
    version='0.1',
    author='Benjamin Alan Weaver',
    author_email='benjamin.weaver@nyu.edu',
    packages=[
        'pydl',
        'pydl.test',
        'pydlutils',
        'pydlutils.bspline',
        'pydlutils.goddard',
        'pydlutils.goddard.astro',
        'pydlutils.goddard.fits',
        'pydlutils.goddard.math',
        'pydlutils.image',
        'pydlutils.mangle',
        'pydlutils.math',
        'pydlutils.misc',
        'pydlutils.sdss',
        'pydlutils.test',
        'pydlspec2d',
        'pydlspec2d.spec1d',
        'pydlspec2d.spec2d',
        ],
    url='http://pypi.python.org/pypi/pydl/',
    license='LICENSE.txt',
    description='Replacement for IDL',
    long_description=open('README.txt').read(),
    classifiers = [ 'Development Status :: 2 - Pre-Alpha',
        'Environment :: Console',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: GNU General Public License (GPL)',
        'Operating System :: POSIX :: Linux',
        'Programming Language :: Python',
        'Topic :: Scientific/Engineering',
        'Topic :: Scientific/Engineering :: Astronomy',
        ],
)

